import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
// import Fs from 'fs'

// var openurl = require("openurl")
// const open = require("open")

// var ccxt = require ('ccxt')
// console.log (ccxt.exchanges.length) // output 123
// console.log (ccxt.exchanges) // print all available exchanges
// <iframe> {"https://testnet.binancefuture.com/en/futures/BTCUSDT"} </iframe>

              // <li><a className="nav-link   scrollto" href="#portfolio">Connect to DEX</a></li>
              // <li><a className="nav-link scrollto" href="#contact">Contact</a></li>
              // <li><a className="getstarted scrollto" href="login.html">Login</a></li>
            

export default function Home() {
  // const google = require("openurl").open('https://google.com')
  // https://testnet.binancefuture.com/en/futures/BTCUSDT
  // {...src="https://testnet.binancefuture.com/en/futures/BTCUSDT"}
  return (
    <div className={styles.container}>
      <Head>
        <title>LiquidDEX App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="./favicon.ico" />
      </Head>
      <div className={styles.logo}>
          <a href="https://www.liquiddex.io/"> <Image src="/LiquidDex-logo-light.png" alt="LiquidDEX Logo" width={146} height={32} /> 
          </a>
        </div>

      <main className={styles.main}>
        <h1 className={styles.title}>
          One Platform for Algo Trading <a href="https://www.liquiddex.io">LiquidDEX</a>
        </h1>
        <p className={styles.description}>
          Auto Trading Gateway to Hummingbot & Exchanges {' '}
         </p>
        <div className={styles.grid}>
          <a href="https://www.liquiddex.io" className={styles.card}>
            <h2>Connect to Hummingbot &rarr;</h2>
          </a>
          <a href="https://www.liquiddex.io" className={styles.card}>
            <h2>Connect via CCXT &rarr;</h2>
          </a>
        </div>
        <div>
         <Image src="/liquidDEX-trading.png" alt="LiquidDEX Logo" width={960} height={640} />
        </div>
        
      </main>

      <footer className={styles.footer}>
        
      </footer>
    </div>
  )
}
